/**
 * Supabase database types for the `public` schema.
 *
 * GENERATED by scripts/generate-database-types.mjs from the database the
 * portable core and the recipe build. Do not edit: run
 *
 *   npm run generate:database-types
 *
 * and commit the result. CI regenerates it and fails on any difference.
 *
 * @see docs/connectors/supabase/database.md — schema, RLS, and connection docs
 * @see docs/erd.mmd — entity relationship diagram
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.15"
  }
  public: {
    Tables: {
      agent_messages: {
        Row: {
          created_at: string
          id: string
          kind: string
          payload: NonNullable<Json>
          seq: number
          session_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          kind: string
          payload: NonNullable<Json>
          seq: number
          session_id: string
        }
        Update: {
          created_at?: string
          id?: string
          kind?: string
          payload?: NonNullable<Json>
          seq?: number
          session_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "agent_messages_session_id_fkey"
            columns: ["session_id"]
            referencedRelation: "agent_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      agent_sessions: {
        Row: {
          created_at: string
          created_by: string
          id: string
          title: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string
          id: string
          title?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string
          id?: string
          title?: string
          updated_at?: string
        }
        Relationships: []
      }
      audit_findings: {
        Row: {
          cell_ids: string[]
          cell_keys: string[]
          check_key: string
          created_at: string
          effort: string | null
          fingerprint: string
          id: string
          impact: string | null
          run_id: string
          service_id: string
          severity: string
          source: string
          status: string
          summary: string | null
          updated_at: string
        }
        Insert: {
          cell_ids?: string[]
          cell_keys?: string[]
          check_key: string
          created_at?: string
          effort?: string | null
          fingerprint: string
          id?: string
          impact?: string | null
          run_id: string
          service_id: string
          severity: string
          source: string
          status?: string
          summary?: string | null
          updated_at?: string
        }
        Update: {
          cell_ids?: string[]
          cell_keys?: string[]
          check_key?: string
          created_at?: string
          effort?: string | null
          fingerprint?: string
          id?: string
          impact?: string | null
          run_id?: string
          service_id?: string
          severity?: string
          source?: string
          status?: string
          summary?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_findings_service_id_fkey"
            columns: ["service_id"]
            referencedRelation: "services"
            referencedColumns: ["id"]
          },
        ]
      }
      authoring_changes: {
        Row: {
          affected_slices: NonNullable<Json>
          agent_session_id: string | null
          args: NonNullable<Json>
          at: string
          author: string
          author_id: string | null
          deleted_kind: string | null
          fn: string
          id: string
          label: string | null
          payload: Json | null
          revert: Json | null
        }
        Insert: {
          affected_slices?: NonNullable<Json>
          agent_session_id?: string | null
          args?: NonNullable<Json>
          at?: string
          author?: string
          author_id?: string | null
          deleted_kind?: string | null
          fn: string
          id?: string
          label?: string | null
          payload?: Json | null
          revert?: Json | null
        }
        Update: {
          affected_slices?: NonNullable<Json>
          agent_session_id?: string | null
          args?: NonNullable<Json>
          at?: string
          author?: string
          author_id?: string | null
          deleted_kind?: string | null
          fn?: string
          id?: string
          label?: string | null
          payload?: Json | null
          revert?: Json | null
        }
        Relationships: []
      }
      business_models: {
        Row: {
          created_at: string
          created_by: string | null
          delivery_cost: string | null
          funding: string | null
          partners: string | null
          pricing: string | null
          revenue_model: string | null
          service_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          delivery_cost?: string | null
          funding?: string | null
          partners?: string | null
          pricing?: string | null
          revenue_model?: string | null
          service_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          delivery_cost?: string | null
          funding?: string | null
          partners?: string | null
          pricing?: string | null
          revenue_model?: string | null
          service_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "business_models_service_id_fkey"
            columns: ["service_id"]
            referencedRelation: "services"
            referencedColumns: ["id"]
          },
        ]
      }
      cell_dependencies: {
        Row: {
          created_at: string
          id: string
          kind: string
          name: string | null
          note: string | null
          source_cell_id: string
          target_cell_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          kind?: string
          name?: string | null
          note?: string | null
          source_cell_id: string
          target_cell_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          kind?: string
          name?: string | null
          note?: string | null
          source_cell_id?: string
          target_cell_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "cell_dependencies_source_cell_id_fkey"
            columns: ["source_cell_id"]
            referencedRelation: "cells"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cell_dependencies_target_cell_id_fkey"
            columns: ["target_cell_id"]
            referencedRelation: "cells"
            referencedColumns: ["id"]
          },
        ]
      }
      cell_touchpoints: {
        Row: {
          cell_id: string
          created_at: string
          id: string
          name: string | null
          origin: string
          position: number
          role: string | null
          summary: string | null
          touchpoint_id: string | null
          updated_at: string
        }
        Insert: {
          cell_id: string
          created_at?: string
          id?: string
          name?: string | null
          origin: string
          position: number
          role?: string | null
          summary?: string | null
          touchpoint_id?: string | null
          updated_at?: string
        }
        Update: {
          cell_id?: string
          created_at?: string
          id?: string
          name?: string | null
          origin?: string
          position?: number
          role?: string | null
          summary?: string | null
          touchpoint_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "cell_touchpoints_cell_id_fkey"
            columns: ["cell_id"]
            referencedRelation: "cells"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cell_touchpoints_touchpoint_id_fkey"
            columns: ["touchpoint_id"]
            referencedRelation: "touchpoints"
            referencedColumns: ["id"]
          },
        ]
      }
      cells: {
        Row: {
          cell_key: string | null
          content: string
          created_at: string
          form: string | null
          frame: string | null
          function: string | null
          id: string
          lane_id: string
          origin: string
          owner: string | null
          path_id: string
          perceived_owner: string | null
          position: number
          status: string
          step_id: string
          summary: string | null
          updated_at: string
          value_props: NonNullable<Json>
        }
        Insert: {
          cell_key?: string | null
          content?: string
          created_at?: string
          form?: string | null
          frame?: string | null
          function?: string | null
          id?: string
          lane_id: string
          origin?: string
          owner?: string | null
          path_id: string
          perceived_owner?: string | null
          position?: number
          status?: string
          step_id: string
          summary?: string | null
          updated_at?: string
          value_props?: NonNullable<Json>
        }
        Update: {
          cell_key?: string | null
          content?: string
          created_at?: string
          form?: string | null
          frame?: string | null
          function?: string | null
          id?: string
          lane_id?: string
          origin?: string
          owner?: string | null
          path_id?: string
          perceived_owner?: string | null
          position?: number
          status?: string
          step_id?: string
          summary?: string | null
          updated_at?: string
          value_props?: NonNullable<Json>
        }
        Relationships: [
          {
            foreignKeyName: "cells_lane_id_fkey"
            columns: ["lane_id"]
            referencedRelation: "lanes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cells_path_id_fkey"
            columns: ["path_id"]
            referencedRelation: "paths"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cells_step_id_fkey"
            columns: ["step_id"]
            referencedRelation: "steps"
            referencedColumns: ["id"]
          },
        ]
      }
      evidence: {
        Row: {
          added_by: string | null
          cell_id: string | null
          cell_key: string | null
          created_at: string
          created_by: string | null
          id: string
          kind: string
          note: string | null
          observed_at: string | null
          proposition_question_key: string | null
          service_id: string
          title: string
          updated_at: string
        }
        Insert: {
          added_by?: string | null
          cell_id?: string | null
          cell_key?: string | null
          created_at?: string
          created_by?: string | null
          id?: string
          kind: string
          note?: string | null
          observed_at?: string | null
          proposition_question_key?: string | null
          service_id: string
          title: string
          updated_at?: string
        }
        Update: {
          added_by?: string | null
          cell_id?: string | null
          cell_key?: string | null
          created_at?: string
          created_by?: string | null
          id?: string
          kind?: string
          note?: string | null
          observed_at?: string | null
          proposition_question_key?: string | null
          service_id?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "evidence_service_id_fkey"
            columns: ["service_id"]
            referencedRelation: "services"
            referencedColumns: ["id"]
          },
        ]
      }
      lanes: {
        Row: {
          created_at: string
          id: string
          kpis: NonNullable<Json>
          lane_role: string | null
          name: string
          origin: string
          owner_team: string | null
          path_id: string
          position: number
          stakeholder_id: string | null
          tools: NonNullable<Json>
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          kpis?: NonNullable<Json>
          lane_role?: string | null
          name: string
          origin?: string
          owner_team?: string | null
          path_id: string
          position?: number
          stakeholder_id?: string | null
          tools?: NonNullable<Json>
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          kpis?: NonNullable<Json>
          lane_role?: string | null
          name?: string
          origin?: string
          owner_team?: string | null
          path_id?: string
          position?: number
          stakeholder_id?: string | null
          tools?: NonNullable<Json>
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "lanes_path_id_fkey"
            columns: ["path_id"]
            referencedRelation: "paths"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lanes_stakeholder_id_fkey"
            columns: ["stakeholder_id"]
            referencedRelation: "stakeholders"
            referencedColumns: ["id"]
          },
        ]
      }
      path_steps: {
        Row: {
          created_at: string
          path_id: string
          position: number
          step_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          path_id: string
          position?: number
          step_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          path_id?: string
          position?: number
          step_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "path_steps_path_id_fkey"
            columns: ["path_id"]
            referencedRelation: "paths"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "path_steps_step_id_fkey"
            columns: ["step_id"]
            referencedRelation: "steps"
            referencedColumns: ["id"]
          },
        ]
      }
      paths: {
        Row: {
          created_at: string
          id: string
          kind: string
          name: string
          note: string | null
          origin: string
          scenario_id: string
          status: string
          summary: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          kind: string
          name: string
          note?: string | null
          origin?: string
          scenario_id: string
          status?: string
          summary?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          kind?: string
          name?: string
          note?: string | null
          origin?: string
          scenario_id?: string
          status?: string
          summary?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "paths_scenario_id_fkey"
            columns: ["scenario_id"]
            referencedRelation: "scenarios"
            referencedColumns: ["id"]
          },
        ]
      }
      phases: {
        Row: {
          business_impact: string | null
          created_at: string
          id: string
          loops_to_phase_id: string | null
          name: string
          operational_requirements: string | null
          origin: string
          position: number
          service_id: string
          summary: string | null
          updated_at: string
        }
        Insert: {
          business_impact?: string | null
          created_at?: string
          id?: string
          loops_to_phase_id?: string | null
          name: string
          operational_requirements?: string | null
          origin?: string
          position?: number
          service_id: string
          summary?: string | null
          updated_at?: string
        }
        Update: {
          business_impact?: string | null
          created_at?: string
          id?: string
          loops_to_phase_id?: string | null
          name?: string
          operational_requirements?: string | null
          origin?: string
          position?: number
          service_id?: string
          summary?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "phases_loops_to_phase_id_fkey"
            columns: ["loops_to_phase_id"]
            referencedRelation: "phases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "phases_service_id_fkey"
            columns: ["service_id"]
            referencedRelation: "services"
            referencedColumns: ["id"]
          },
        ]
      }
      resources: {
        Row: {
          cell_id: string
          cell_touchpoint_id: string | null
          created_at: string
          featured: boolean
          id: string
          kind: string
          name: string
          origin: string
          position: number
          updated_at: string
          url: string | null
        }
        Insert: {
          cell_id: string
          cell_touchpoint_id?: string | null
          created_at?: string
          featured?: boolean
          id?: string
          kind?: string
          name: string
          origin: string
          position: number
          updated_at?: string
          url?: string | null
        }
        Update: {
          cell_id?: string
          cell_touchpoint_id?: string | null
          created_at?: string
          featured?: boolean
          id?: string
          kind?: string
          name?: string
          origin?: string
          position?: number
          updated_at?: string
          url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "resources_cell_id_fkey"
            columns: ["cell_id"]
            referencedRelation: "cells"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "resources_placement_in_cell_fkey"
            columns: ["cell_touchpoint_id", "cell_id"]
            referencedRelation: "cell_touchpoints"
            referencedColumns: ["id", "cell_id"]
          },
        ]
      }
      scenarios: {
        Row: {
          created_at: string
          id: string
          layout: string
          name: string
          note: string | null
          origin: string
          phase_id: string
          position: number
          summary: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          layout?: string
          name: string
          note?: string | null
          origin?: string
          phase_id: string
          position?: number
          summary?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          layout?: string
          name?: string
          note?: string | null
          origin?: string
          phase_id?: string
          position?: number
          summary?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "scenarios_phase_id_fkey"
            columns: ["phase_id"]
            referencedRelation: "phases"
            referencedColumns: ["id"]
          },
        ]
      }
      schema_version: {
        Row: {
          applied_at: string
          singleton: boolean
          version: string
        }
        Insert: {
          applied_at?: string
          singleton?: boolean
          version: string
        }
        Update: {
          applied_at?: string
          singleton?: boolean
          version?: string
        }
        Relationships: []
      }
      service_account_emails: {
        Row: {
          created_at: string
          email: string
          note: string | null
        }
        Insert: {
          created_at?: string
          email: string
          note?: string | null
        }
        Update: {
          created_at?: string
          email?: string
          note?: string | null
        }
        Relationships: []
      }
      services: {
        Row: {
          created_at: string
          entity_examples: NonNullable<Json>
          id: string
          name: string
          slug: string | null
          summary: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          entity_examples?: NonNullable<Json>
          id?: string
          name: string
          slug?: string | null
          summary?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          entity_examples?: NonNullable<Json>
          id?: string
          name?: string
          slug?: string | null
          summary?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      slices: {
        Row: {
          actor: string | null
          authorship: string
          created_at: string
          created_by: string | null
          id: string
          kind: string
          locale: string
          position: number
          service_id: string
          summary: string | null
          title: string
          updated_at: string
        }
        Insert: {
          actor?: string | null
          authorship?: string
          created_at?: string
          created_by?: string | null
          id?: string
          kind: string
          locale?: string
          position?: number
          service_id: string
          summary?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          actor?: string | null
          authorship?: string
          created_at?: string
          created_by?: string | null
          id?: string
          kind?: string
          locale?: string
          position?: number
          service_id?: string
          summary?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "slices_service_id_fkey"
            columns: ["service_id"]
            referencedRelation: "services"
            referencedColumns: ["id"]
          },
        ]
      }
      slide_images: {
        Row: {
          cell_id: string | null
          id: string
          image_url: string | null
          position: number
          slide_id: string
        }
        Insert: {
          cell_id?: string | null
          id?: string
          image_url?: string | null
          position: number
          slide_id: string
        }
        Update: {
          cell_id?: string | null
          id?: string
          image_url?: string | null
          position?: number
          slide_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "slide_images_cell_id_fkey"
            columns: ["cell_id"]
            referencedRelation: "cells"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "slide_images_slide_id_fkey"
            columns: ["slide_id"]
            referencedRelation: "slides"
            referencedColumns: ["id"]
          },
        ]
      }
      slides: {
        Row: {
          caption: string | null
          cell_ids: string[]
          cell_keys: string[]
          created_at: string
          created_by: string | null
          id: string
          position: number
          shows_all_images: boolean
          slice_id: string
          title: string | null
          updated_at: string
        }
        Insert: {
          caption?: string | null
          cell_ids?: string[]
          cell_keys?: string[]
          created_at?: string
          created_by?: string | null
          id?: string
          position: number
          shows_all_images?: boolean
          slice_id: string
          title?: string | null
          updated_at?: string
        }
        Update: {
          caption?: string | null
          cell_ids?: string[]
          cell_keys?: string[]
          created_at?: string
          created_by?: string | null
          id?: string
          position?: number
          shows_all_images?: boolean
          slice_id?: string
          title?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "slides_slice_id_fkey"
            columns: ["slice_id"]
            referencedRelation: "slices"
            referencedColumns: ["id"]
          },
        ]
      }
      stakeholders: {
        Row: {
          aliases: string[]
          created_at: string
          id: string
          kind: string
          name: string
          part_of_id: string | null
          summary: string | null
          updated_at: string
        }
        Insert: {
          aliases?: string[]
          created_at?: string
          id?: string
          kind: string
          name: string
          part_of_id?: string | null
          summary?: string | null
          updated_at?: string
        }
        Update: {
          aliases?: string[]
          created_at?: string
          id?: string
          kind?: string
          name?: string
          part_of_id?: string | null
          summary?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "stakeholders_parent_id_fkey"
            columns: ["part_of_id"]
            referencedRelation: "stakeholders"
            referencedColumns: ["id"]
          },
        ]
      }
      steps: {
        Row: {
          created_at: string
          id: string
          name: string
          origin: string
          scenario_id: string
          summary: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          origin?: string
          scenario_id: string
          summary?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          origin?: string
          scenario_id?: string
          summary?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "steps_scenario_id_fkey"
            columns: ["scenario_id"]
            referencedRelation: "scenarios"
            referencedColumns: ["id"]
          },
        ]
      }
      touchpoints: {
        Row: {
          aliases: string[] | null
          created_at: string
          icon_url: string | null
          id: string
          kind: string
          name: string
          origin: string
          stakeholder_id: string | null
          summary: string | null
          tone: string | null
          updated_at: string
          url: string | null
        }
        Insert: {
          aliases?: string[] | null
          created_at?: string
          icon_url?: string | null
          id?: string
          kind?: string
          name: string
          origin: string
          stakeholder_id?: string | null
          summary?: string | null
          tone?: string | null
          updated_at?: string
          url?: string | null
        }
        Update: {
          aliases?: string[] | null
          created_at?: string
          icon_url?: string | null
          id?: string
          kind?: string
          name?: string
          origin?: string
          stakeholder_id?: string | null
          summary?: string | null
          tone?: string | null
          updated_at?: string
          url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "touchpoints_stakeholder_id_fkey"
            columns: ["stakeholder_id"]
            referencedRelation: "stakeholders"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      evidence_counts: {
        Row: {
          cell_id: string | null
          n: number | null
        }
        Relationships: []
      }
      trash: {
        Row: {
          affected_slices: Json | null
          deleted_at: string | null
          deleted_by: string | null
          id: string | null
          kind: string | null
          label: string | null
          payload: Json | null
        }
        Insert: {
          affected_slices?: Json | null
          deleted_at?: string | null
          deleted_by?: string | null
          id?: string | null
          kind?: string | null
          label?: string | null
          payload?: Json | null
        }
        Update: {
          affected_slices?: Json | null
          deleted_at?: string | null
          deleted_by?: string | null
          id?: string | null
          kind?: string | null
          label?: string | null
          payload?: Json | null
        }
        Relationships: []
      }
    }
    Functions: {
      add_lane: {
        Args: {
          at_position?: number
          lane_role?: string
          name: string
          scenario_id: string
        }
        Returns: string[]
      }
      add_step: {
        Args: { at_position?: number; name: string; path_id: string }
        Returns: string
      }
      cell_natural_key: { Args: { cell_id: string }; Returns: string }
      clear_cell_dependency: {
        Args: { dependency_id: string }
        Returns: undefined
      }
      create_path: {
        Args: {
          kind?: string
          lane_source_path_id?: string
          name: string
          scenario_id: string
        }
        Returns: string
      }
      create_phase: {
        Args: { name: string; service_id: string; summary?: string }
        Returns: string
      }
      create_scenario: {
        Args: {
          lane_set?: Json
          lane_source_path_id?: string
          layout?: string
          name: string
          path_name?: string
          phase_id: string
          step_count?: number
        }
        Returns: Json
      }
      delete_cell: { Args: { cell_id: string }; Returns: string }
      delete_path: { Args: { path_id: string }; Returns: string }
      delete_scenario: { Args: { scenario_id: string }; Returns: string }
      deletion_impact: {
        Args: { kind: string; scope_id?: string; target_id: string }
        Returns: Json
      }
      duplicate_path: {
        Args: {
          copy_cells?: boolean
          copy_dependencies?: boolean
          kind?: string
          name: string
          source_path_id: string
        }
        Returns: string
      }
      duplicate_scenario: {
        Args: { name: string; source_scenario_id: string }
        Returns: string
      }
      is_service_account: { Args: Record<PropertyKey, never>; Returns: boolean }
      key_slug: { Args: { value: string }; Returns: string }
      mint_cell_key: {
        Args: { lane_id: string; path_id: string; step_id: string }
        Returns: string
      }
      record_authoring_change: {
        Args: {
          agent_session_id?: string
          args?: Json
          author?: string
          fn: string
          revert?: Json
        }
        Returns: string
      }
      remove_lane: {
        Args: { lane_name: string; scenario_id: string }
        Returns: string
      }
      remove_lanes: { Args: { lane_ids: string[] }; Returns: string }
      remove_placement: { Args: { p_placement_id: string }; Returns: Json }
      remove_step: {
        Args: { path_id: string; step_id: string }
        Returns: string
      }
      rename_content_item: {
        Args: { p_content: string; p_from: string; p_to: string }
        Returns: string
      }
      rename_owner_tag: {
        Args: { from_name: string; to_name: string }
        Returns: string[]
      }
      rename_path: {
        Args: { new_name: string; path_id: string }
        Returns: undefined
      }
      rename_phase: {
        Args: { new_name: string; phase_id: string }
        Returns: undefined
      }
      rename_scenario: {
        Args: { new_name: string; scenario_id: string }
        Returns: undefined
      }
      rename_touchpoint: {
        Args: { p_name: string; p_touchpoint_id: string }
        Returns: Json
      }
      reorder_lanes: {
        Args: { lane_names: string[]; scenario_id: string }
        Returns: undefined
      }
      reorder_steps: {
        Args: { path_id: string; step_ids: string[] }
        Returns: undefined
      }
      restore_cell_content: {
        Args: { cell_id: string; content: string }
        Returns: undefined
      }
      restore_cell_dependency: {
        Args: { dependency_id: string; name: string; note: string }
        Returns: undefined
      }
      restore_cell_touchpoints: {
        Args: { p_cell_id: string; p_rows: Json }
        Returns: undefined
      }
      restore_featured_resources: { Args: { p_rows: Json }; Returns: undefined }
      restore_placement: {
        Args: { p_resources?: Json; p_row: Json }
        Returns: Json
      }
      schema_comments: {
        Args: Record<PropertyKey, never>
        Returns: {
          column_name: string
          comment: string
          relation: string
        }[]
      }
      set_cell_dependency: {
        Args: {
          kind?: string
          name?: string
          note?: string
          source_cell_id: string
          target_cell_id: string
        }
        Returns: Json
      }
      set_cell_featured_image: {
        Args: { cell_id: string; image_url: string }
        Returns: Json
      }
      set_featured_resource: {
        Args: { p_featured: boolean; p_resource_id: string }
        Returns: Json
      }
      set_path_steps: {
        Args: { path_id: string; step_ids: string[] }
        Returns: undefined
      }
      set_placement_touchpoint: {
        Args: {
          p_name?: string
          p_placement_id: string
          p_touchpoint_id?: string
        }
        Returns: Json
      }
      slices_referencing: { Args: { cell_ids: string[] }; Returns: Json }
      sync_cell_resources: {
        Args: { p_cell_id: string; p_rows: Json }
        Returns: undefined
      }
      sync_cell_touchpoints: {
        Args: { p_cell_id: string; p_names: string[] }
        Returns: Json
      }
      sync_placement_resources: {
        Args: { p_placement_id: string; p_rows: Json }
        Returns: undefined
      }
      update_cell_dependency: {
        Args: {
          dependency_id: string
          kind: string
          note: string
          target_cell_id: string
        }
        Returns: Json
      }
      update_scenario_layout: {
        Args: { layout: string; scenario_id: string }
        Returns: undefined
      }
      update_touchpoint: {
        Args: {
          p_icon_url: string
          p_kind: string
          p_name: string
          p_summary: string
          p_touchpoint_id: string
          p_url: string
        }
        Returns: Json
      }
      upsert_cell: {
        Args: {
          content: string
          lane_id: string
          path_id: string
          step_id: string
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const

// ---------------------------------------------------------------------------
// Derived with the file above by scripts/generate-database-types.mjs: the
// unions are read off the constraints that close each vocabulary, and the
// aliases are the names the codebase imports. Edit the generator, not this.
// ---------------------------------------------------------------------------

/** The `entity_status` domain, shared by `cells.status` and `paths.status`. */
export type EntityStatus =
  | 'proposed'
  | 'planned'
  | 'built'
  | 'live'
  | 'at_risk'
  | 'deprecated'

/** The kinds of Path a Scenario holds. */
export type PathKind =
  | 'happy'
  | 'variant'
  | 'exception'

/** Who a Stakeholder is to the service. */
export type StakeholderKind =
  | 'recipient'
  | 'staff'
  | 'partner'
  | 'provider'
  | 'team'

/** The closed vocabulary of `lanes.lane_role`; a null role renders as a plain swimlane. */
export type LaneRole =
  | 'customer_actions'
  | 'frontstage_actions'
  | 'backstage_actions'
  | 'partner_actions'
  | 'frontstage_touchpoints'
  | 'backstage_touchpoints'
  | 'support_actions'
  | 'storyboard'

export type Cell = Database['public']['Tables']['cells']['Row']
export type CellDependency = Database['public']['Tables']['cell_dependencies']['Row']
export type Lane = Database['public']['Tables']['lanes']['Row']
export type Stakeholder = Database['public']['Tables']['stakeholders']['Row']
export type Path = Database['public']['Tables']['paths']['Row']
export type PathStep = Database['public']['Tables']['path_steps']['Row']
export type Phase = Database['public']['Tables']['phases']['Row']
export type Service = Database['public']['Tables']['services']['Row']
export type Scenario = Database['public']['Tables']['scenarios']['Row']
export type Step = Database['public']['Tables']['steps']['Row']
export type Slice = Database['public']['Tables']['slices']['Row']
export type SlideImage = Database['public']['Tables']['slide_images']['Row']
export type Slide = Database['public']['Tables']['slides']['Row'] & {
  slide_images?: SlideImage[]
}
export type Evidence = Database['public']['Tables']['evidence']['Row']
export type Finding = Database['public']['Tables']['audit_findings']['Row']
export type EvidenceCount = Database['public']['Views']['evidence_counts']['Row']
